### PR TITLE
Enable swift package manager

### PR DESCRIPTION
**Pull request by maxwellainatchi**
Added a Package.swift to enable requiring it as a SwiftPM dependency

### CODE REVIEW

**Review by coolbnjmn — APPROVED** [review]
Sorry it took me so long to get to this, thanks for this contribution! I don't use SPM, but looks to me like this is the way to get that support :)

Thanks again

**Comment by maxwellainatchi** [comment]
Thanks @coolbnjmn! Can you post a patch release on GH releases so that it can be pulled from SwiftPM?

**Comment by coolbnjmn** [comment]
Done @maxwellainatchi -- lmk if you still can't pull this from SwiftPM :)

**Comment by maxwellainatchi** [comment]
@coolbnjmn just tried, works great! 🎉

**Pull request merged**
