### PR TITLE
Adding UIBarButton item support

### PR DESCRIPTION
**Pull request by ManueGE**
Answering to #7 , this pull request adds `UIBarButtonItem` support.

### CODE REVIEW

**Comment by coolbnjmn** [comment]
Hi @ManueGE 

Thanks for the PR! I just merged in another, older PR and seems I may have caused some merge conflicts here. Would you mind updating your PR, and I can merge it from there?

Thanks!

**Comment by ManueGE** [comment]
Sure!

**Comment by ManueGE** [comment]
It's done now!

**Comment by coolbnjmn** [comment]
Thanks!

**Pull request merged**
