### PR TITLE
ActionKit as framework and simpler UIGestureRecognizer() init

### PR DESCRIPTION
**Pull request by irlabs**
I converted the project into a framework, so it can be build with Carthage and be easily added and imported in your project.

Also I added a default value to the `name` argument in the convenience init of the UIGestureRecognizer extension for easier usage if no name is necessary.

### CODE REVIEW

**Comment by coolbnjmn** [comment]
Hi Dirk, 

As a framework, is it also possible to drag and drop it into a project still? And does this mean we are ready for Cocoapods?

Thanks

**Comment by irlabs** [comment]
Hi Benjamin,

I left the three source files of ActionKit intact, so you can still drag and drop them wherever you like in your project.

If you want to make this into a CocoaPod, just create a .podspec for it. CocoaPods 0.36 supports frameworks, so that should be fine too. (I just didn't work with CocoaPods recently, so YMMV)

**Comment by irlabs** [comment]
Hi Benjamin,

I fixed some project details settings, so it's now cleaner and easier to get running on your machine. (the project was too specific before).

Could you consider merging this pull request into your version?  
We would like to start a swift 2.0 branch, but only if we can import it as a .framework.

Thanks

**Comment by coolbnjmn** [comment]
Will do so ASAP.

Thanks so much for your work

**Pull request merged**
